### PR TITLE
Disabled the selection till save is success for bios setting

### PR DESCRIPTION
**Pull request by Renuka9527**
Description: Disabled the selection till save is success for bios setting
Defect: https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=595828

github Issue: https://github.com/ibm-openbmc/openbmc/issues/291

### CODE REVIEW

**Review by Nikhil-Ashoka — CHANGES_REQUESTED** [review]
We have linux KVM percentage dropdown as well. Instead of disabling everything in the page, We can try to remove the get call that is causing the issue.

**Comment by Renuka9527** [comment]
> We have linux KVM percentage dropdown as well. Instead of disabling everything in the page, We can try to remove the get call that is causing the issue.

Addressed

**Review by SteffiAntony — APPROVED** [review]

**Comment by Nikhil-Ashoka** [comment]
I think we still have to keep the disabled implementation in this page. The change we made might not reproduce the issue in our systems, but will happen in some systems

**Comment by Renuka9527** [comment]
> I think we still have to keep the disabled implementation in this page. The change we made might not reproduce the issue in our systems, but will happen in some systems

Addressed

**Review by Nikhil-Ashoka — APPROVED** [review]

**Pull request merged**
