### PR TITLE
Removed Downloading the Empty Audit log files when download API is failing from GUI.

### PR DESCRIPTION
**Pull request by Renuka9527**
Description: Audit log files are empty when downloaded from GUI. Removed downloading the audit log files when the API is failing.
Defect: https://jazz07.rchland.ibm.com:13443/jazz/resource/itemName/com.ibm.team.workitem.WorkItem/600910
Screenshot:
image

### CODE REVIEW

**Comment by mzipse** [comment]
Renuka, I haven't looked at your code changes but if I understand from the title, it sounds like you are removing the option to download if there is a failure.  I don't think that's the right thing to do.  Instead, this defect should get routed to the backend team (ie. Janet Adkins) so she can sort out why the backend is failing.  Let me know if I'm confused.

**Comment by Renuka9527** [comment]
> Renuka, I haven't looked at your code changes but if I understand from the title, it sounds like you are removing the option to download if there is a failure. I don't think that's the right thing to do. Instead, this defect should get routed to the backend team (ie. Janet Adkins) so she can sort out why the backend is failing. Let me know if I'm confused.

@mzipse Title might be confusing, We are not removing the option to download. It is just that earlier we are downloading Empty the Audit log file, When the API is failing. But with these changes, User can still have the download option, we are not downloading any empty log files if the API fails. Instead we are throwing the Error notification to User as Error downloading logs.
image

**Comment by Nikhil-Ashoka** [comment]
Also, this is a part of the fix, I think, it is failing to download would be a backend issue.

**Comment by Nikhil-Ashoka** [comment]
> Renuka, I haven't looked at your code changes but if I understand from the title, it sounds like you are removing the option to download if there is a failure. I don't think that's the right thing to do. Instead, this defect should get routed to the backend team (ie. Janet Adkins) so she can sort out why the backend is failing. Let me know if I'm confused.

I think, we should not download if the API is failing, Am I right Maury?

**Comment by Renuka9527** [comment]
> Also, this is a part of the fix, I think, it is failing to download would be a backend issue.

Yes, Backend API issue, We can route to Janet. From GUI perspective we are not downloading any empty logs if API fails.

**Comment by mzipse** [comment]
Thanks for the clarification!  And Yes, I think I agree if the API fails, we should not download anything.  If there is an API fail, we can always get a BMC dump (with the audit log file in it) to figure out why it failed.

**Review by SteffiAntony — APPROVED** [review]

**Review by Nikhil-Ashoka — APPROVED** [review]

**Pull request merged**
