### PR TITLE
Upgraded the Axios verison

### PR DESCRIPTION
**Pull request by Nikhil-Ashoka**
- Upgraded the axios version from 0.21.4 to 1.6.0
- Defect: https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=603937

### CODE REVIEW

**Comment by gtmills** [comment]
How did you test? 
Can you push this upsteam?

**Review by joseph-reynolds — APPROVED** [review]
The axois changes look good.  I am approving those.  But there are also changes to other packages removed, added, and new checksums.  Are these intended?

**Comment by Nikhil-Ashoka** [comment]
> How did you test? Can you push this upsteam?

Hey Gunnar, Not sure how to test it, Any suggestions, Looked into this https://github.com/axios/axios/issues/6022#issuecomment-1781906904. Seems that this issue would be solved.
Yes, I will also, create a commit for upstream.

**Comment by Nikhil-Ashoka** [comment]
> The axois changes look good. I am approving those. But there are also changes to other packages removed, added, and new checksums. Are these intended?

Yes, The only packages that is updated will be in package.json file. 

package-lock.json is automatically generated for any operations where npm modifies either the node_modules tree, or package.json. These are intended.

**Review by Renuka9527 — APPROVED** [review]

**Review by vedangimittal — APPROVED** [review]

**Pull request merged**
