### PR TITLE
Match PLDM: correct Gard to Guard

### PR DESCRIPTION
**Pull request by gtmills**
Fixes 586859

This is 1060 only.

https://github.com/ibm-openbmc/pldm/pull/478 went into 1060 and changed the spelling of pvm_rpd_gard_policy to pvm_rpd_guard_policy. Need to match that bios attribute spelling.

Tested: 

A Nikhil
  [9:34 AM](https://ibm-systems-power.slack.com/archives/D02S91FMF5F/p1701275674154069)
Hi Gunnar, The changes are working as expected.

### CODE REVIEW

**Comment by Nikhil-Ashoka** [comment]
Also, Change need to be made in translation file.

**Comment by Nikhil-Ashoka** [comment]
image

**Comment by gtmills** [comment]
I tried to change everywhere. 
Used 
grep -R 'gard'  --exclude=*NoticesText.vue  *

to find.

**Review by Nikhil-Ashoka — APPROVED** [review]

**Comment by Nikhil-Ashoka** [comment]
image

**Review by ArchanaKakani — APPROVED** [review]

**Comment by Nikhil-Ashoka** [comment]
image

**Review by jaypadath — APPROVED** [review]

**Pull request merged**
